### ISSUE TITLE
Started with error！

### ISSUE THREAD

**Issue by nengc** [cppcoffee/netguard#15]
I started with the root privilege, but still "Operation not permitted"
![image](https://github.com/user-attachments/assets/ed993eb4-a2a8-4d2a-9dd9-25f391950d68)

**Comment by cppcoffee** [comment]
In my current local x86_64 CPU testing, I haven't been able to reproduce the issue.

The main branch has committed logic to print more detailed logs:

https://github.com/cppcoffee/netguard/pull/16/files#diff-7e7e78c0de1698bd34e0f33a1e47d5b9d60d5448d30f8f4a6e3ef513bf1d699dR87-R108

You can run it to see the output. Additionally, could you please provide more information about the operating system and other relevant details?

like:

```
# uname -a
# lsb_release -a
# chrt -m
```

**Comment by nengc** [comment]
hi @cppcoffee ,pulled the latest code, but have no detailed info.
![image](https://github.com/user-attachments/assets/022f9b9c-8d59-4e61-b5a5-17f92df59067)

but i changed to the below:
![image](https://github.com/user-attachments/assets/94fb7039-8de5-4541-adbb-963d20f29f6f)

Shows
![image](https://github.com/user-attachments/assets/ac7da786-96f9-4d9d-b4af-4b7644741621)

![image](https://github.com/user-attachments/assets/9128fd8c-750f-4634-84a2-b96ce533baec)

![image](https://github.com/user-attachments/assets/3605a1b3-1f7b-44ee-ac11-ce5ddd38a814)

**Comment by cppcoffee** [comment]
You source code looks old. can compare the main branch:

https://github.com/cppcoffee/netguard/blob/main/server/src/util.rs#L81-L112

**Comment by nengc** [comment]
hi @cppcoffee , in my server, the code is the latest. But still have no more detailed error info.
![image](https://github.com/user-attachments/assets/8064b253-b8d2-4f1c-94e5-5fa8ef1b2aa3)

**Comment by cppcoffee** [comment]
Instead of setting the thread real-time priority, modify it to `let policy = libc::SCHED_OTHER`.

**Comment by nengc** [comment]
Hi @cppcoffee , started with no error now. But why i can still open the app with the port 9091
![image](https://github.com/user-attachments/assets/57b55c39-4828-47e8-9149-eeede8581f56)

**Comment by cppcoffee** [comment]
Check that the configuration file is configured correctly, especially `allow_ips`, and accessed using another machine:

https://github.com/cppcoffee/netguard/blob/main/server/config/netguard.toml#L40

**Comment by nengc** [comment]
Hi @cppcoffee, I checked the ``allow_ips``, but still not work. 
And using the "netguard-tool" from the Windows, also have no response both from the client and server.
 ``.\netguard-tool.exe auth --server 【server ip】 --dport 54 --protocol=udp --unlock 9091 --key=./rsa``

![image](https://github.com/user-attachments/assets/fb3425b8-a3d6-42b9-b493-43561762f64c)

![image](https://github.com/user-attachments/assets/ed3030da-c26f-4d0e-813a-1e2507123eb1)

But when i using the "netguard-tool" from the Linux server, it works.
![image](https://github.com/user-attachments/assets/ab559e36-bf96-4463-b719-ca9947c68b70)
![image](https://github.com/user-attachments/assets/e30e605e-a985-419d-84cb-e0cf21a5f326)

**Comment by cppcoffee** [comment]
No support for windows, not tested.

**Comment by nengc** [comment]
Oh, that will be very helpful if support Windows.
@cppcoffee 
And i tested in the Linux server, set the ``allow_ips`` to ``[]`` , still not work.

**Comment by cppcoffee** [comment]
What is your version of iptables? print a list of rules:

```shell
# iptables --version
# iptables -L
```

`netguard-server` relies on `iptables`, make sure it is started.

**Comment by nengc** [comment]
@cppcoffee seems ok
![image](https://github.com/user-attachments/assets/abc1ccf6-0c87-4254-87bc-648f2bcd34cc)
![image](https://github.com/user-attachments/assets/540a7b78-d50a-4e32-bdc3-5742b7399c80)
![image](https://github.com/user-attachments/assets/409445d5-70c6-4a4b-bc03-468dbcbd28fe)

**Comment by cppcoffee** [comment]
Is `iptables` or `ufw` running?

> `netguard-server` relies on `iptables`, make sure it is started.

**Comment by nengc** [comment]
@cppcoffee oh, the iptables is not running! tks.
Have the plan to support Windows , Mac or other platform?

**Comment by nengc** [comment]
@cppcoffee oh, the iptables is not running! tks.
Have the plan to support Windows , Mac or other platform?

**Comment by nengc** [comment]
Hi, @cppcoffee 
oh, another problem, the 9091 blocked, but after i unlocked the port, still cannot open the app.
![image](https://github.com/user-attachments/assets/09d5494d-db23-4957-ab34-622fc47e8cf7)
![image](https://github.com/user-attachments/assets/19a6c29b-2f2c-4166-b96f-8f3b65a2baab)

And in the intranet，all the src IPs are the same.

**Comment by cppcoffee** [comment]
On windows platforms, you need to specify the interface of the sending NIC.

> using the "netguard-tool" from the Windows, also have no response both from the client and server. `.\netguard-tool.exe auth --server 【server ip】 --dport 54 --protocol=udp --unlock 9091 --key=./rsa`

**Comment by cppcoffee** [comment]
If the protocol is TCP, you need to use tcp to send the packet.

https://github.com/cppcoffee/netguard/blob/main/server/src/worker.rs#L233
https://github.com/cppcoffee/netguard/blob/main/server/src/worker.rs#L254

**Comment by nengc** [comment]
Hi @cppcoffee, tks for your reply. But still not work
![image](https://github.com/user-attachments/assets/afeca05e-d3cd-4fe0-912b-924421404f47)
![image](https://github.com/user-attachments/assets/ee69a0c9-fa40-441c-a155-201768c1fbab)

**Comment by cppcoffee** [comment]
To determine whether the other party has received the verification packet, there will be log output. If no packet is received, it's highly likely that it was lost in transit.

output message reference:

https://github.com/cppcoffee/netguard/blob/main/server/src/worker.rs#L261-L264

**Comment by cppcoffee** [comment]
It is recommended to first run this on two machines within a local area network (LAN) or metropolitan area network (MAN).
